export default {
    USERS_RECEIVED: 'USERS_RECEIVED',
    USERSITEM_RECEIVED: 'USERSITEM_RECEIVED',
    USERSITEM_SELECTED: 'USERSITEM_SELECTED',
    USERSITEM_UN_SELECTED: 'USERSITEM_UN_SELECTED'
  }